name: Run Robot Framework Tests for W3Schools SQL Page

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Use Ubuntu runner (you can also use windows-latest or macos-latest if needed)
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # Check out the repository code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Set the Python version (adjust if needed)

      - name: Install Robot Framework and SeleniumLibrary
        run: |
          python -m pip install --upgrade pip
          pip install robotframework  # Install Robot Framework
          pip install robotframework-seleniumlibrary  # Install SeleniumLibrary
          sudo apt-get install -y chromium-browser  # Install Chromium browser

      - name: Set up Chrome for Selenium
        run: |
          export DISPLAY=:99  # Set display for the browser
          nohup Xvfb :99 &  # Run Xvfb for headless display

      - name: Run Robot Framework Test
        run: |
          robot open_w3schools_sql.robot  # Run the test script (adjust path if necessary)

      - name: Upload Robot Framework Test Results
        uses: actions/upload-artifact@v3  # Upload test result files
        with:
          name: robot-test-results
          path: output/*.xml  # Path to the Robot Framework result XML files

