---
workflow:
  name: 'Run Robot Framework Tests for W3Schools SQL Page'
  trigger:
    push:
      branch: 'main'
    pull_request:
      branch: 'main'
  jobs:
    job:
      name: 'test'
      runs-on: 'ubuntu-latest'
      steps:
        step:
          - name: 'Checkout Repository'
            uses: 'actions/checkout@v2'
          - name: 'Set up Python'
            uses: 'actions/setup-python@v2'
            with:
              python-version: 3.9
          - name: 'Install Robot Framework and SeleniumLibrary'
            run: "python -m pip install --upgrade pip\n            pip install robotframework\n            pip install robotframework-seleniumlibrary\n            sudo apt-get update\n            sudo apt-get install -y chromium-browser\n            sudo apt-get install -y xvfb"
          - name: 'Install ChromeDriver'
            run: "CHROMIUM_VERSION=$(chromium-browser --version | sed 's/[^0-9]*\\([0-9]*\\.[0-9]*\\.[0-9]*\\)\\..*/\\1/')\n            echo \"Chromium version: $CHROMIUM_VERSION\"\n            wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip\n            unzip chromedriver_linux64.zip\n            sudo mv chromedriver /usr/local/bin/"
          - name: 'Set up Chrome for Selenium'
            run: "export DISPLAY=:99\n            nohup Xvfb :99 &"
          - name: 'Run Robot Framework Test'
            run: 'robot open_w3schools_sql.robot'
          - name: 'Upload Robot Framework Test Results'
            uses: 'actions/upload-artifact@v3'
            with:
              name: 'robot-test-results'
              path: 'output/*.xml'
          - name: 'Debugging: List Installed Packages'
            run: "pip freeze\n            chromium-browser --version\n            chromedriver --version"
          - name: 'Debugging: Check if Xvfb is running'
            run: 'ps aux | grep Xvfb'
